#!/usr/bin/env bash

set -eo pipefail

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
# shellcheck source=script/vars
. "${ROOT}/script/vars"

aws s3 cp "s3://${SECRETS_BUCKET}/secrets.txt" "${ROOT}/priv/secrets.txt" \
    --sse aws:kms \
    --sse-kms-key-id "$SECRETS_KEY_ID"
