#!/usr/bin/env bash

set -eo pipefail

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
# shellcheck source=script/vars
. "${ROOT}/script/vars"

if ! [ -f "${ROOT}/priv/secrets.txt" ]; then
    echo "Secrets file does not exist!"
    exit 1
fi

aws s3 cp "${ROOT}/priv/secrets.txt" "s3://${SECRETS_BUCKET}/secrets.txt" \
    --sse aws:kms \
    --sse-kms-key-id "$SECRETS_KEY_ID"
