#!/usr/bin/env bash

set -euo pipefail

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
# shellcheck source=script/vars
. "${ROOT}/script/vars"

aws s3 mb "s3://${SECRETS_BUCKET}"
aws s3api put-bucket-versioning --bucket "$SECRETS_BUCKET" --versioning-configuration "Status=Enabled"
if aws s3 ls "s3://${SECRETS_BUCKET}/secrets.txt" > /dev/null; then
    # shellcheck source=script/get_secrets
    . "${ROOT}/script/get_secrets"
else
    touch "${ROOT}/priv/secrets.txt"
fi

echo "Edit ${ROOT}/priv/secrets.txt and then run script/put_secrets"
