#!/usr/bin/env bash

set -exo pipefail

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
export ROOT
export REPLACE_OS_VARS=true
HOST_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
export HOST_IP
"${ROOT}/bin/deployable" ping
