#!/usr/bin/env bash

REGION=us-east-1
DEPLOY_BUCKET=deployable-code
CONFIG_BUCKET=deployable-config
SECRETS_BUCKET=deployable-secrets
KEY_PAIR_NAME=deployable
STACK_NAME=deployable
SECRETS_KEY_ID=88b115a2-15e8-4701-bb2f-4e1b2191a7fe

export REGION
export DEPLOY_BUCKET
export CONFIG_BUCKET
export SECRETS_BUCKET
export KEY_PAIR_NAME
export STACK_NAME
export SECRETS_KEY_ID
