#!/usr/bin/env bash

set -exo pipefail

# A bunch of AWS preliminaries

REGION=$(curl http://169.254.169.254/latest/dynamic/instance-identity/document|grep region|awk -F\" '{print $4}')
export NODE_IPS=$(aws ec2 describe-instances \
                      --filters "Name=tag:AutoScalingGroupName,Values=Deployable" \
                      --output text \
                      --query  "Reservations[*].Instances[*].PrivateIpAddress" \
                      --region "$REGION")

export ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
export PORT=4000
export REPLACE_OS_VARS=true
export HOST_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
"$ROOT"/bin/deployable start
