#!/usr/bin/env bash

set -exo pipefail
export ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
export REPLACE_OS_VARS=true
export HOST_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
"$ROOT"/bin/deployable ping
